### ISSUE TITLE
Training/Finetuning questions

### ISSUE THREAD

**Issue by kynthesis** [csxmli2016/textbsr#7]
Hi Xiaoming Li,

Thank you for your outstanding research.
How can we train or finetune the `bsrgan_text_256.pth` file?
And the datasets we should use to train/finetune the model further.
Can you share more details about this project?
I want to do research based on your excellent `textbsr`.

Best regards,
Khoa D. Vo

**Comment by csxmli2016** [comment]
> Hi Xiaoming Li,
> 
> Thank you for your outstanding research. How can we train or finetune the `bsrgan_text_256.pth` file? And the datasets we should use to train/finetune the model further. Can you share more details about this project? I want to do research based on your excellent `textbsr`.
> 
> Best regards, Khoa D. Vo

Hi Khoa D. Vo,
As for the network and training code, you can follow [BSRGAN](https://github.com/cszn/BSRGAN) or [Real-ESRGAN](https://github.com/xinntao/Real-ESRGAN).
The most different thing is the synthetic training data. You can refer to [A simple demo for synthesizing the training Data](https://github.com/csxmli2016/MARCONet/tree/main/Train) of our work [MARCONet](https://github.com/csxmli2016/MARCONet).

**Comment by kynthesis** [comment]
Thank you very much for your quick response!

**Comment by kynthesis** [comment]
Hello Xiaoming Li,

Please allow me to ask you a few questions!

- How many data samples have you used to train bsrgan_text_256? I trained with a dataset of 100.000 samples, but it doesn't seem enough. Now, I'm training with 1.000.000 samples.
- Can you give more details about batch size, number of iterations, number of GPUs, or related settings that may affect the training progress? I'm using a training config of batch size 12, iteration 400.000.

At the moment, I'm training with only 1 RTX 4090 with batch size 12, which may not be enough for this project.

Best regards,
Khoa D. Vo

**Comment by csxmli2016** [comment]
> Hello Xiaoming Li,
> 
> Please allow me to ask you a few questions!
> 
> * How many data samples have you used to train bsrgan_text_256? I trained with a dataset of 100.000 samples, but it doesn't seem enough. Now, I'm training with 1.000.000 samples.
> * Can you give more details about batch size, number of iterations, number of GPUs, or related settings that may affect the training progress? I'm using a training config of batch size 12, iteration 400.000.
> 
> At the moment, I'm training with only 1 RTX 4090 with batch size 12, which may not be enough for this project.
> 
> Best regards, Khoa D. Vo

The GPU server is enough for training this project. Since this work does not need the long sentence as input, you can synthesize input with a resolution of 128*128 or 128*256 for training (that means only one or two characters). This project is very easy to train. It takes nearly one or two days using one GPU to get a stable result.

**Comment by kynthesis** [comment]
BSRGAN_TEXT_256 (Your pre-trained model)
![z5231953897576_76a6dcc9b08264f0698a9144af1158b7_BSRGANText](https://github.com/csxmli2016/textbsr/assets/113872127/f5db3105-65cd-464e-b87a-6a25148f1fd8)
Real-ESRGAN (My training model)
![z5231953897576_76a6dcc9b08264f0698a9144af1158b7_BSRGANText](https://github.com/csxmli2016/textbsr/assets/113872127/32d53e7b-2454-4446-9605-6f05041e8a6b)

I tried many settings but still failed to train a stable model like yours.
Can you please give me some directions?

**Comment by csxmli2016** [comment]
> BSRGAN_TEXT_256 (Your pre-trained model) ![z5231953897576_76a6dcc9b08264f0698a9144af1158b7_BSRGANText](https://private-user-images.githubusercontent.com/113872127/317929603-f5db3105-65cd-464e-b87a-6a25148f1fd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2Nzc5MjAsIm5iZiI6MTcxMTY3NzYyMCwicGF0aCI6Ii8xMTM4NzIxMjcvMzE3OTI5NjAzLWY1ZGIzMTA1LTY1Y2QtNDY0ZS1iODdhLTZhMjUxNDhmMWZkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQwMjAwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODE5Nzc1OGFmNjBkYjhiZmIyZGMxMDc2YzczMzIwZTFmM2ViNjhlNTI0YzBlODkxNzk1MjY2Yjc1ZjNlNjhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HuSALyFRYrw6Bjvyn6FDLUByrgRmaXkAK2-AQrODG54) Real-ESRGAN (My training model) ![z5231953897576_76a6dcc9b08264f0698a9144af1158b7_BSRGANText](https://private-user-images.githubusercontent.com/113872127/317929634-32d53e7b-2454-4446-9605-6f05041e8a6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2Nzc5MjAsIm5iZiI6MTcxMTY3NzYyMCwicGF0aCI6Ii8xMTM4NzIxMjcvMzE3OTI5NjM0LTMyZDUzZTdiLTI0NTQtNDQ0Ni05NjA1LTZmMDUwNDFlOGE2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQwMjAwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTJhYWE1MGU3ZDI5NjlhZjRiZTljNjJiZGFlODg3YTAyMzBlNDczNzU5OTg1MThkNDA3NjVmYmIwNjdjMDcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QuNu0U5ak-UPuOmJfJ9it9scCl09Dv6KWPfgJfGlWzE)
> 
> I tried many settings but still failed to train a stable model like yours. Can you please give me some directions?

How about the training process? You can use tensorboard to visualize the training images, including LR input, SR result, and ground-truth.
